apiVersion: v1
kind: Service
metadata:
  name: my-python-app1-lb
spec:
  type: LoadBalancer
  ports:
    - port: 32000
      targetPort: 5000
      protocol: TCP
  selector:
    app: my-python-app1
    tier: app