apiVersion: cv1
kind: Pod
metadata:
  name: my-ubuntu
  labels:
    app: my-ubuntu
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/sleep", "3650d"]
      imagePullPolicy: IfNotPresent
  restartPolicy: Always