apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-ubuntu
  labels:
    app: my-ubuntu
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-ubuntu
  template:
    metadata:
      labels:
        app: my-ubuntu
    spec:
      containers:
        - name: ubuntu
          image: ubuntu
          command: ["/bin/sleep", "3650d"]
          imagePullPolicy: IfNotPresent
      restartPolicy: Always